# Example annotated build data file
mod-name: ConformalDecals
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata: # Include these gamedata-level folders in packages:
    - ConformalDecals
  included-support:  # Include these root-level files in packages
    - README.md
    - LICENSE-ART.md
    - LICENSE-SOURCE.md
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    location: url
    url: https://ksp.sarbian.com/jenkins/job/ModuleManager/159/artifact/ModuleManager.4.1.4.dll
    zip: false
  B9PartSwitch:
    location: url
    url: http://pileof.rocks/KSP/B9PartSwitch-v2.18.0.zip
    zip: true
  Shabby:
    location: url
    url: http://pileof.rocks/KSP/Shabby_v0.2.0.zip
    zip: true
  HarmonyKSP:
    location: url
    url: https://github.com/KSPModdingLibs/HarmonyKSP/releases/download/2.0.4.0/HarmonyKSP_2.0.4.0_for_KSP1.8+.zip
    zip: true
deploy:
  SpaceDock:
    enabled: true # activate/deactivate this deployment script
    mod-id: 2451  # The Spacedock mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script