# Example annotated build data file
mod-name: ConformalDecals
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata: # Include these gamedata-level folders in packages:
    - ConformalDecals
  included-support:  # Include these root-level files in packages
    - README.md
    - LICENSE-ART.md
    - LICENSE-SOURCE.md
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    location: url
    url: https://ksp.sarbian.com/jenkins/job/ModuleManager/157/artifact/ModuleManager.4.1.3.dll
    zip: false
  B9PartSwitch:
    location: url
    url: http://pileof.rocks/KSP/B9PartSwitch-v2.16.0.zip
    zip: true
  Shabby:
    location: url
    url: http://taniwha.org/~bill/Shabby_v0.1.2.zip
    zip: true
deploy:
  - SpaceDock:
      enabled: true # activate/deactivate this deployment script
      mod-id: 2451  # The Spacedock mod ID for deployment
  - GitHub:
      enabled: true  # activate/deactivate this deployment script